
/**
 * Fetches the OpenAPI spec from the Chatterbox TTS API and generates TypeScript types.
 *
 * Usage:
 * - CHATTERBOX_API_URL=https://your-api-url npm run sync-api
 *
 * Or with a .env file:
 * - npm run sync-api
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// import "dotenv/config";
import openapiTS, { astToString, SchemaObject } from "openapi-typescript";

export const baseUrl = "https://marketapi20260604105905-ajfqchdfakgbhggm.canadacentral-01.azurewebsites.net"

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// You can change the output path/name to whatever you prefer.
const OUTPUT_PATH = path.resolve(
  __dirname,
  "../types/api.d.ts"
);

async function main() {


  // Change this if your OpenAPI spec is hosted somewhere else.
  const openApiUrl = `${baseUrl}/swagger/v1/swagger.json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);


  // 1️⃣ Fetch JSON instead of passing URL directly
  const response = await fetch(openApiUrl);
  if (!response.ok) throw new Error(`Failed to fetch OpenAPI spec: ${response.status}`);
  const spec = await response.json();


  // 2️⃣ Make all properties required in all schemas
  const schemas: Record<string, SchemaObject> = spec.components?.schemas || {};
  for (const schema of Object.values(schemas)) {
    if (schema.type === "object" && schema.properties) {
      schema.required = Object.keys(schema.properties);
    }
  }

  const ast = await openapiTS(spec);
  const contents = astToString(ast);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Add header comment
  const header = `/**
 * This file is auto-generated by scripts/sync-api.ts
 * Do not edit manually. Run \`npm run sync-api\` to regenerate.
 *
 * Generated from: ${openApiUrl}
 * Generated at: ${new Date().toISOString()}
 */\n`;

  fs.writeFileSync(OUTPUT_PATH, header + contents);
  console.log(`Types written to: ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error("Failed to sync API types:", err);
  process.exit(1);
});
